### ISSUE TITLE
我已经加载了Mpadata，但是不知道如何在屏幕上呈现。

### ISSUE THREAD

**Issue by baekgoms** [HonorLee-cn/CGTool#3]
我是新手！我已经加载了Mpadata，但是不知道如何在屏幕上呈现。
我使用的客户端地图是1000。我将CGTool放在资产中使用。
在问题＃2中，您已经在Unity屏幕上绘制了客户端地图，非常感谢您告诉我如何操作！
我看过Crossgate-Survivors，但它只是使用了精灵进行配置。我想要做的是在屏幕上绘制现有的法兰城地图！

![t1](https://github.com/HonorLee-cn/CGTool/assets/28751354/65f3bff6-ec81-4cf9-bcd1-d91487c90620)

**Comment by HonorLee-cn** [comment]
我将在3天内进行更新.
除提供部分更新外,另外会对相关功能使用示例example进行提交,届时可通过相关代码来学习使用

**Comment by baekgoms** [comment]
谢谢，我会等你的。
